### PR TITLE
fix #210: String(string)

### LINKED ISSUE #210: Broken String conversions
I'm getting
```
julia> Compat.String("foo")
ERROR: TypeError: typeassert: expected AbstractString, got Tuple{ASCIIString}
 in call at /Users/stevenj/.julia/v0.4/Compat/src/Compat.jl:37
```
on Julia 0.4, apparently as a consequence of #206 (cc @quinnj).

This seems to be the source of stevengj/PyCall.jl#281

### PR DESCRIPTION
**Pull request by stevengj**
This fixes #210.

Note that it doesn't make sense to accept multiple string arguments to `String`, since in Julia 0.5 only `String(s::AbstractString)` exists.

### CODE REVIEW

File: src/Compat.jl [hunk 1]
```diff
@@ -34,7 +34,7 @@ else
         call(::Type{Base.ByteString},io::Base.AbstractIOBuffer) = bytestring(io::Base.AbstractIOBuffer)
         call(::Type{Base.ByteString},p::Union{Ptr{Int8},Ptr{UInt8}}) = bytestring(p::Union{Ptr{Int8},Ptr{UInt8}})
         call(::Type{Base.ByteString},p::Union{Ptr{Int8},Ptr{UInt8}}, len::Integer) = bytestring(p::Union{Ptr{Int8},Ptr{UInt8}}, len::Integer)
-        call(::Type{Base.ByteString},s...) = bytestring(s::AbstractString...)
+        call(::Type{Base.ByteString},s::AbstractString) = bytestring(s)
```
Comment (yuyichao) [inline src/Compat.jl]: Mind deleting the excess type assertions above too?

Comment (stevengj) [inline src/Compat.jl]: done.

**Comment by stevengj** [comment]
Can we get a new version tag asap?

**Comment by tkelman** [comment]
yeah no objections to tagging this right away
