### PR TITLE
Add `Fix{N}` for fixing a single positional argument at any position

### LINKED ISSUE #828: Add `Fix{N}` utility for fixing an argument
I'm eager to use the `Fix{N}` syntax from https://github.com/JuliaLang/julia/pull/54653 in older Julia versions. It should be backwards compatible except for the multiple dispatch component.

### PR DESCRIPTION
**Pull request by MilesCranmer**
Adds https://github.com/JuliaLang/julia/pull/54653.

Fixes #828.

```julia
julia> using Compat: Fix

julia> map(Fix{3}(muladd, 1.0), 1:3, 4:6)
3-element Vector{Float64}:
  5.0
 11.0
 19.0
```

---

**Multiple dispatch**: This is a bit of an edge case, and presumably many functions in Compat are like this, but since `Fix1` is broadly used:

Note that even with this PR, `Compat.Fix{1}` is not the same as `Base.Fix1` on Julia versions earlier than `1.12.0-DEV.966`. Therefore, if you wish to use this as a way to dispatch on `Fix{N}` for libraries compatible with Julia earlier than v1.12, you should declare a function both for `Compat.Fix{1}` as well as `Base.Fix1`. You can do this with a

```julia
@static if !isdefined(Base, :Fix)
    #= Declare additional methods for Compat.Fix =#
end
```

### CODE REVIEW

**Review by mcabbott — APPROVED** [review]
LGTM, but I don't have merge rights.

**Comment by MilesCranmer** [comment]
@martinholters would you be willing to take a look

File: src/Compat.jl [hunk 1]
```diff
@@ -1122,6 +1122,67 @@ if VERSION < v"1.8.0-DEV.1016"
     export chopprefix, chopsuffix
 end
 
+# https://github.com/JuliaLang/julia/pull/54653: add Fix
+@static if !isdefined(Base, :Fix)
```
Comment (martinholters) [inline src/Compat.jl:1126]:
```suggestion
@static if !isdefined(Base, :Fix) # VERSION < v"1.12.0-DEV.981"
```
(Can leave the condition as is, but having the Julia version noted comes handy once we set about weeding out old stuff.)

**Review by martinholters — COMMENTED** [review]
>Note that even with this PR, `Compat.Fix{1}` is not the same as `Base.Fix1` on Julia versions earlier than `1.12.0-DEV.966`. Therefore, if you wish to use this as a way to dispatch on `Fix{N}` for libraries compatible with Julia earlier than v1.12, you should declare a function both for `Compat.Fix{1}` as well as `Base.Fix1`.

Should this be documented somewhere more findable than the PR description?

Apart from that LGTM.

File: README.md [hunk 2]
```diff
@@ -72,6 +72,8 @@ changes in `julia`.
 
 ## Supported features
 
+* `Fix{N}` which fixes an argument at the `N`th position ([#54653]) (since Compat 4.16.0)
```
Comment (martinholters) [inline README.md:75]:
```suggestion
* `Compat.Fix{N}` which fixes an argument at the `N`th position ([#54653]) (since Compat 4.16.0)
```

**Comment by MilesCranmer** [comment]
> Should this be documented somewhere more findable than the PR description?

I’ll add it to the docs for the function

**Comment by MilesCranmer** [comment]
Done.

**Review by martinholters — APPROVED** [review]
LGTM. Barring objections, I'll merge this and #830 tomorrow and tag a new version.

**Comment by MilesCranmer** [comment]
Great, thanks!
